# Generated by Django 5.2 on 2025-04-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='last_watered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='light_requirements',
            field=models.CharField(blank=True, choices=[('LOW', 'Low Light'), ('MEDIUM', 'Medium Light'), ('HIGH', 'Bright Light')], default='MEDIUM', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='water_frequency',
            field=models.IntegerField(blank=True, help_text='Number of days between watering', null=True),
        ),
    ]
