# Generated by Django 5.2 on 2025-04-29 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_plant_last_watered_plant_light_requirements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fertilization date')),
                ('type', models.CharField(choices=[('O', 'Organic'), ('S', 'Synthetic'), ('N', 'Natural')], default='O', max_length=1)),
                ('amount', models.CharField(choices=[('L', 'Light'), ('M', 'Moderate'), ('H', 'Heavy')], default='M', max_length=1)),
                ('notes', models.TextField(blank=True, max_length=250)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Watering date')),
                ('amount', models.CharField(choices=[('L', 'Light'), ('M', 'Moderate'), ('H', 'Heavy')], default='M', max_length=1)),
                ('notes', models.TextField(blank=True, max_length=250)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
