# Generated by Django 5.2 on 2025-04-29 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_plant_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='plant',
            name='age',
            field=models.IntegerField(help_text='Approximate age in years (0 for new plants)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(help_text="Share some details about your plant's appearance, history, or care requirements", max_length=250),
        ),
        migrations.AlterField(
            model_name='plant',
            name='last_watered',
            field=models.DateField(blank=True, help_text='The last date this plant was watered', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='light_requirements',
            field=models.CharField(choices=[('LOW', 'Low Light - Indirect light, no direct sun'), ('MEDIUM', 'Medium Light - Bright indirect light'), ('HIGH', 'Bright Light - Direct sunlight needed')], default='MEDIUM', help_text='Select the amount of light your plant needs', max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(help_text='Give your plant a unique name', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='species',
            field=models.CharField(help_text='The botanical or common name of your plant', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_frequency',
            field=models.IntegerField(help_text='Number of days between watering', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Watering Frequency'),
        ),
    ]
