# Generated by Django 5.2 on 2025-04-29 07:41

from django.db import migrations

def set_default_water_frequency(apps, schema_editor):
    Plant = apps.get_model('main_app', 'Plant')
    for plant in Plant.objects.all():
        if plant.water_frequency is None:
            plant.water_frequency = 7  # Default to weekly watering
        plant.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_plant_options_alter_plant_age_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_water_frequency),
    ]
