# Generated by Django 5.2 on 2025-04-29 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20250429_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='water_frequency',
            field=models.IntegerField(blank=True, default=7, help_text='Number of days between watering', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Watering Frequency'),
        ),
    ]
